version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    env_file:
    - path: ./app/.env
  redis:
    image: redis:7.2.4-alpine
    restart: always
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel debug
    volumes: 
      - redis:/data
  worker:
    build:
      context: ./worker
      target: dev
    command: yarn dev
    restart: always
    env_file:
    - path: ./app/.env
    volumes:
      - ./worker:/app
      - ./worker/node_modules:/app/node_modules
    depends_on:
      - redis
      - mongo
  frontend:
    build:
      context: ./app
      target: dev
    restart: always
    command: yarn dev
    env_file:
    - path: ./app/.env
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
      - ./app/.next:/app/.next
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo
      - worker
volumes:
  redis:
    driver: local